# Generated by Django 6.0b1 on 2026-01-30 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('image', models.BinaryField(blank=True, null=True)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('preparation', models.CharField(blank=True, max_length=1000, null=True)),
                ('ingredients', models.CharField(blank=True, max_length=1000, null=True)),
                ('time', models.IntegerField()),
                ('difficulty', models.IntegerField()),
                ('image', models.BinaryField(blank=True, null=True)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=36, unique=True)),
                ('user_id', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='RecipeCategories',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rest_api.category')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rest_api.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rest_api.user'),
        ),
        migrations.CreateModel(
            name='UserFavoriteRecipes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rest_api.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rest_api.user')),
            ],
        ),
    ]
