# Generated by Django 6.0b1 on 2026-01-30 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='recipe',
            table='recipe',
        ),
        migrations.AlterModelTable(
            name='recipecategories',
            table='recipe_categories',
        ),
        migrations.AlterModelTable(
            name='session',
            table='session',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.AlterModelTable(
            name='userfavoriterecipes',
            table='user_favorite_recipes',
        ),
    ]
